### ISSUE TITLE
Support i3 config or it's own

### ISSUE THREAD

**Issue by zlamalp** [denesb/xfce4-i3-workspaces-plugin#10]
Hi, first of all, great work. I have just two issues. I didn't find the way to configure workspace switcher font/color. Font is displayed as black (red for urgent) and it's not much readable on dark xfce4-panel. It would be nice, if it could read config form i3 config file or it had own config options like other xfce4 widgets.

Also, my workspaces are renamed. "2" is in a fact "2:[image font] WEB". It's correctly displayed but when I click on it, it either crashes or open new workpsace named "2". As bonus, it would be nice, if it would respect "strip_workspace_numbers yes" option in i3 config file.

Thanks for consideration.

**Comment by denesb** [comment]
Hello, thanks for your suggestions, I will add configurable properties for font colour (normal, urgent) and strip_workspace_number.

**Comment by denesb** [comment]
And of course I will fix the crash. :)
