### ISSUE TITLE
Plugin retrieves information from wrong i3 session

### ISSUE THREAD

**Issue by lasers** [denesb/xfce4-i3-workspaces-plugin#11]
I missed having XDG menu in i3 so I played with XFCE4 panel a bit... as well as a full blown XFCE desktop environment. I then saw your plugin. I installed it and saw an issue right away.

Right now, I have two Xorg servers running.

DISPLAY=:0.0  -- (Two monitors) Running i3wm (Two monitors)
DISPLAY=:0.1 -- (One monitor) Running i3wm + XFCE4 panel + i3-workspaces-plugin.

It does not print the correct numbers. It's displaying the first one.
1,2  |  6 -- When it should be... 1

**Comment by denesb** [comment]
Man this is going to be tough... :)
At the moment I have no idea how the plugin behaves on multi-monitor or even less on multi Xorg server setups, as I have only one monitor (and only one Xorg server running).
I'll try to research into how this could be solved.

**Comment by denesb** [comment]
Thanks for the extra information. I planned the other issues to a closer milestone anyway as they were reported first.
About the status applet: I miss that too, but currently I'm fine with the various xfce4-panel status applets. There are severeal of them like NetworkSpeedMonitor, CPUGraph, SystemLoadMonitor, etc. Of course they are not as flexible or configurable as the ones you mentioned or conky but it's better than nothing.

**Comment by lasers** [comment]
Thanks to Nvidia. I am able to use one DISPLAY with two GPU. I am able to load xfce4-panel on all outputs (Using 3 panels). Closing. Many thanks. :100:

**Comment by denesb** [comment]
Excellent, I am glad you were able to solve it.
