### ISSUE TITLE
"urgent" event is not handled when a workspace changes from "urgent" to "normal"

### ISSUE THREAD

**Issue by xuhdev** [denesb/xfce4-i3-workspaces-plugin#13]
If "urgent" workspace is the currently focused workspace, and one unurgent the workspace without leaving the workspace, the red button does not turn normal.

Also, switching to the urgent workspace, in my opnion, shouldn't unurgent the workspace; the workspace should be unurgent after the urgent window is focused. So I guess the best way is to handle the "urgent" event in both direction.

acrisci/i3ipc-glib#3

**Comment by denesb** [comment]
Merge request #14 should fix this. If the problem still persists please reopen.
