### ISSUE TITLE
After renaming a workspace, the panel is not updated until switching back to the workspace

### ISSUE THREAD

**Issue by ad1217** [denesb/xfce4-i3-workspaces-plugin#15]
If a workspace is (re)named, the workspace does not change in the panel, and stays "focused" (in the panel) when switching away. When switching to one of these workspaces, the applet seems to refresh all of them, reseting the focus and applying the naming.

**Comment by denesb** [comment]
Yes, it only refreshes the workspace array when you switch workspace. I think there should be some even for rename too. I will look into it.

**Comment by ad1217** [comment]
Works great now, thanks!
