### ISSUE TITLE
Disappearing Panel

### ISSUE THREAD

**Issue by Foggalong** [denesb/xfce4-i3-workspaces-plugin#21]
Steps to replicate:

1. have i3 in XFCE panel
2. open terminal in workspace 1
3. open Steam game in workspace 2 in window mode (not fullscreen)
4. click within the window of the steam game
5. move back to workspace 1

*expected*: moves back to workspace 1
*actual*: moves back but XFCE panel becomes invisible

The process is still there and the empty space is visible on screen but the panel itself is visible. Panel registers no clicks either. It seems hit and miss whether this happens, but I've only had it happen when this plugin is installed and part of the panel. I have i3 gaps installed so if I click in the gap around the Steam game window before moving workspace this seems to stop this happening, but I don't always remember :(

Doing `killall xfce4-panel && xfce4-panel` brings it back as normal.

**Comment by denesb** [comment]
I'm not sure this is actually a plugin bug. Can you try the following:
1. Remove the i3 workspaces plugin from the panel.
2. Do the same steps that lead to reproduce the bug and see if you can reproduce it without the plugin too.

**Comment by Foggalong** [comment]
Sorry, not noticed you'd replied! Yeah I've reproduced it without the plugin in the panel so I'm guessing it's to do with something else.
