### ISSUE TITLE
Color for visible non-focused workspaces?

### ISSUE THREAD

**Issue by ad1217** [denesb/xfce4-i3-workspaces-plugin#23]
It would be useful to have another color (or some other indicator) for workspaces that are visible, but not focused. In multi-monitor setups, it is currently not possible to tell which workspace is visible on another monitor.

**Comment by denesb** [comment]
Fine by me, the problem is I wouldn't be able to test this if I were to add the functionality as I don't have two monitors. But if somebody adds it I'll merge it happily.

**Comment by worblehat** [comment]
I am working on a patch. Any suggestions how visible non-focused workspaces should be displayed (color, weight, ...)?

**Comment by ad1217** [comment]
I was thinking of doing it as a different color (with another setting).

**Comment by worblehat** [comment]
Should I implement it or do you planed to do it?

**Comment by denesb** [comment]
I would do it but it would be working blind as I would have no mean to actually test if it works (having just one monitor). So if you feel like it, by all means do it. Thank you.

**Comment by worblehat** [comment]
Looks like this is not as trivial as it seems to be. But maybe I am missing something:
There is no event for visibility-changes of workspaces in i3's IPC and events related to outputs (monitors) are [not implemented](https://i3wm.org/docs/ipc.html#_output_event) yet. So as far as I see, we have to handle workspaces getting visible/invisible but not focused in [on_focus_workspace()](https://github.com/denesb/xfce4-i3-workspaces-plugin/blob/9bf5a4c7f63166f2407dd6d32a92c87575de15dc/panel-plugin/i3wm-delegate.c#L544). As the arguments (previous and currently focused workspaces) are not helpful here, the only way I see is to iterate **all workspaces** and check if they are visible or not. Afterwards one would need to call a callback that updates all workspace-buttons. Such a callback does not exist so far.

Any ideas or suggestions?

**Comment by denesb** [comment]
I think iterating over all the workspaces every time the focus changes is totally acceptable. That is how I dealt with some other cases where the events from the window manager did not have enough information. Feel free to add the necessary callbacks.

**Comment by denesb** [comment]
I think this is solved now by #32 as workspaces that are on a different output are not visible (with the correct config).
