### ISSUE TITLE
Set Font Style

### ISSUE THREAD

**Issue by xiamaz** [denesb/xfce4-i3-workspaces-plugin#29]
I want to set all text to bold. There is currently no setting available and the plugin does not heed font_name in gtkrc.
Either settings or theming support would be nice.

**Comment by KarinaBauer** [comment]
+1

**Comment by tommyalatalo** [comment]
Adding font style settings including font size and boldness would be great. After an update my FontAwesome icon fonts display way too small and I can't find any way to work around it.
