### ISSUE TITLE
Cannot build for xfce 12

### ISSUE THREAD

**Issue by guest73** [denesb/xfce4-i3-workspaces-plugin#54]
The required package libxfce4panel-1.0 was not found on your system.
That's because I have  libxfce4panel-2.0 in ubuntu bionic (Mint actually). 
Is there a way to compile it for the latest xfce?

**Comment by denesb** [comment]
You can try to bumping the version number (in `configure.ac.in`)  and see if it still builds.

**Comment by xome4ok** [comment]
Ubuntu bionic has `libxfce4panel-1.0` available in `xfce4-panel-dev` package.

https://packages.ubuntu.com/bionic/amd64/xfce4-panel-dev/filelist
