### ISSUE TITLE
Build in Fedora 29

### ISSUE THREAD

**Issue by ngerke** [denesb/xfce4-i3-workspaces-plugin#55]
I've successfully build the plugin in Fedora 29 XFCE:

```
git clone https://github.com/denesb/xfce4-i3-workspaces-plugin.git
git clone https://github.com/acrisci/i3ipc-glib.git
cd i3ipc-glib
sudo dnf install gtk-doc.x86_64 libtool-2.4.6-27.fc29.x86_64 json-glib-1.4.4-1.fc29.x86_64 json-glib-devel-1.4.4-1.fc29.x86_64 gobject-introspection-1.58.3-1.fc29.x86_64 gobject-introspection-devel-1.58.3-1.fc29.x86_64 redhat-rpm-config
./autogen.sh  --prefix=/usr 
make
sudo make install
cd ..
cd xfce4-i3-workspaces-plugin
sudo dnf install xfce4-dev-tools-4.12.0-8.fc29.x86_64 gtk2-devel-2.24.32-3.fc29.x86_64 gtk2-2.24.32-3.fc29.x86_64 libxfce4ui-4.13.4-20.fc29.x86_64 libxfce4ui-devel-4.13.4-20.fc29.x86_64 libxfce4util-4.13.2-20.fc29.x86_64 libxfce4util-devel-4.13.2-20.fc29.x86_64 xfce4-panel-devel-4.13.3-20.fc29.x86_64
./autogen.sh --prefix=/usr
make
sudo make install
```

**Comment by mietzen** [comment]
@denesb None, but I though it might help somebody else since most of the requiered pkgs have different names compared to the pkgs listed in the README.MD, you could see it as a feature request for the documentation 😉 😄 
Perhabs you like to document the build steps in the README.MD

**Comment by fepitre** [comment]
@ngerke: If you are interested, have a look here: https://github.com/denesb/xfce4-i3-workspaces-plugin/pull/57

**Comment by denesb** [comment]
@ngerke please send a pull-request to add this information to README.md, people will not think to look for build instructions in the issues... they expect to see problems here ;).
