### ISSUE TITLE
Plugin not working with Xfce 4.16

### ISSUE THREAD

**Issue by rharish101** [denesb/xfce4-i3-workspaces-plugin#64]
Xfce 4.16 upgraded libxfce4ui-1 to libxfce4ui-2 instead. Therefore, the currently installed plugin isn't showing up in Xfce panel settings. This also fails to build (due to the libxfce4ui-1 check). The error raised is:
```
checking for libxfce4ui-1 >= 4.8.0... not found
*** The required package libxfce4ui-1 was not found on your system.
*** Please install libxfce4ui-1 (atleast version 4.8.0) or adjust
*** the PKG_CONFIG_PATH environment variable if you
*** installed the package in a nonstandard prefix so that
*** pkg-config is able to find it.
```

**Comment by rharish101** [comment]
Oops, didn't see that pull request #63 was already opened to solve this.

**Comment by denesb** [comment]
#63 was merged, closing this, please reopen if you still see it with that merged.
